// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PetCore.Infrastructure.Persistence;

#nullable disable

namespace PetCore.Infrastructure.Migrations
{
    [DbContext(typeof(PetCoreContext))]
    [Migration("20260911210015_AjustarRelacionamentoPetHistorico")]
    partial class AjustarRelacionamentoPetHistorico
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("PetCore.Domain.Entities.Clinica", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Cnpj")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<Guid>("IdEndereco")
                        .HasColumnType("char(36)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("IdEndereco")
                        .IsUnique();

                    b.ToTable("clinica_petcore", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000001"),
                            Cnpj = "12.345.678/0001-90",
                            IdEndereco = new Guid("10000000-0000-0000-0000-000000000001"),
                            Nome = "PetCore Clínica Centro (fictícia)"
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000002"),
                            Cnpj = "98.765.432/0001-10",
                            IdEndereco = new Guid("10000000-0000-0000-0000-000000000002"),
                            Nome = "PetCore Vet Jardins (fictícia)"
                        });
                });

            modelBuilder.Entity("PetCore.Domain.Entities.Endereco", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Cep")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Complemento")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("endereco_petcore", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000001"),
                            Cep = "01001-000",
                            Complemento = "Sala 12 - dados fictícios"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000002"),
                            Cep = "01415-002",
                            Complemento = "Bloco B - dados fictícios"
                        });
                });

            modelBuilder.Entity("PetCore.Domain.Entities.Exame", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateOnly>("Data")
                        .HasColumnType("date");

                    b.Property<Guid>("IdMedico")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("IdProntuario")
                        .HasColumnType("char(36)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("IdMedico");

                    b.HasIndex("IdProntuario");

                    b.ToTable("exame_petcore", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("80000000-0000-0000-0000-000000000001"),
                            Data = new DateOnly(2025, 5, 10),
                            IdMedico = new Guid("40000000-0000-0000-0000-000000000001"),
                            IdProntuario = new Guid("70000000-0000-0000-0000-000000000001"),
                            Nome = "Hemograma da Luna",
                            Tipo = "Hemograma completo"
                        },
                        new
                        {
                            Id = new Guid("80000000-0000-0000-0000-000000000002"),
                            Data = new DateOnly(2025, 6, 2),
                            IdMedico = new Guid("40000000-0000-0000-0000-000000000002"),
                            IdProntuario = new Guid("70000000-0000-0000-0000-000000000002"),
                            Nome = "Ultrassom do Tobias",
                            Tipo = "Ultrassom abdominal"
                        });
                });

            modelBuilder.Entity("PetCore.Domain.Entities.Historico", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateOnly>("DataAbertura")
                        .HasColumnType("date");

                    b.Property<Guid?>("IdPet")
                        .HasColumnType("char(36)");

                    b.Property<bool>("Status")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("Id");

                    b.HasIndex("IdPet")
                        .IsUnique();

                    b.ToTable("historico_petcore", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000001"),
                            DataAbertura = new DateOnly(2025, 3, 12),
                            IdPet = new Guid("50000000-0000-0000-0000-000000000001"),
                            Status = true
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000002"),
                            DataAbertura = new DateOnly(2025, 4, 8),
                            IdPet = new Guid("50000000-0000-0000-0000-000000000002"),
                            Status = true
                        });
                });

            modelBuilder.Entity("PetCore.Domain.Entities.Medicamento", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Dosagem")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Instrucao")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("medicamento_petcore", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("90000000-0000-0000-0000-000000000001"),
                            Dosagem = "1 comprimido a cada 24 horas",
                            Instrucao = "Administrar após a alimentação por 5 dias.",
                            Nome = "Dermocalm Vet (fictício)"
                        },
                        new
                        {
                            Id = new Guid("90000000-0000-0000-0000-000000000002"),
                            Dosagem = "1/2 comprimido a cada 12 horas",
                            Instrucao = "Administrar conforme prescrição veterinária.",
                            Nome = "CardioPet (fictício)"
                        });
                });

            modelBuilder.Entity("PetCore.Domain.Entities.Medico", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateOnly>("DataNascimento")
                        .HasColumnType("date");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Especialidade")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Sexo")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("varchar(1)");

                    b.Property<string>("Telefone")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("UrlImg")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("medico_petcore", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("40000000-0000-0000-0000-000000000001"),
                            DataNascimento = new DateOnly(1985, 8, 14),
                            Email = "helena.duarte@exemplo.test",
                            Especialidade = "Dermatologia",
                            Nome = "Dra. Helena Duarte",
                            Senha = "SenhaDemo#2026",
                            Sexo = "F",
                            Telefone = "11987654321",
                            UrlImg = "https://exemplo.test/medicos/helena.jpg"
                        },
                        new
                        {
                            Id = new Guid("40000000-0000-0000-0000-000000000002"),
                            DataNascimento = new DateOnly(1982, 2, 20),
                            Email = "rafael.nogueira@exemplo.test",
                            Especialidade = "Cardiologia",
                            Nome = "Dr. Rafael Nogueira",
                            Senha = "SenhaDemo#2026",
                            Sexo = "M",
                            Telefone = "11976543210",
                            UrlImg = "https://exemplo.test/medicos/rafael.jpg"
                        });
                });

            modelBuilder.Entity("PetCore.Domain.Entities.Pet", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateOnly>("DataNasc")
                        .HasColumnType("date");

                    b.Property<string>("Especie")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Pelagem")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Porte")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Raca")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Sexo")
                        .HasColumnType("int");

                    b.Property<bool>("Status")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("UrlImg")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("pet_petcore", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("50000000-0000-0000-0000-000000000001"),
                            DataNasc = new DateOnly(2021, 6, 18),
                            Especie = "Canina",
                            Nome = "Luna",
                            Pelagem = "Dourada",
                            Porte = "Grande",
                            Raca = "Golden Retriever",
                            Sexo = 0,
                            Status = true,
                            UrlImg = "https://exemplo.test/pets/luna.jpg"
                        },
                        new
                        {
                            Id = new Guid("50000000-0000-0000-0000-000000000002"),
                            DataNasc = new DateOnly(2022, 9, 5),
                            Especie = "Felina",
                            Nome = "Tobias",
                            Pelagem = "Creme e marrom",
                            Porte = "Pequeno",
                            Raca = "Siamês",
                            Sexo = 1,
                            Status = true,
                            UrlImg = "https://exemplo.test/pets/tobias.jpg"
                        });
                });

            modelBuilder.Entity("PetCore.Domain.Entities.Prontuario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateOnly>("DataEmissao")
                        .HasColumnType("date");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<Guid>("IdHistorico")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("IdMedico")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("IdHistorico");

                    b.HasIndex("IdMedico");

                    b.ToTable("prontuario_petcore", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("70000000-0000-0000-0000-000000000001"),
                            DataEmissao = new DateOnly(2025, 5, 10),
                            Descricao = "Consulta preventiva; pele sem alterações relevantes.",
                            IdHistorico = new Guid("30000000-0000-0000-0000-000000000001"),
                            IdMedico = new Guid("40000000-0000-0000-0000-000000000001")
                        },
                        new
                        {
                            Id = new Guid("70000000-0000-0000-0000-000000000002"),
                            DataEmissao = new DateOnly(2025, 6, 2),
                            Descricao = "Avaliação de rotina; ausculta cardíaca normal.",
                            IdHistorico = new Guid("30000000-0000-0000-0000-000000000002"),
                            IdMedico = new Guid("40000000-0000-0000-0000-000000000002")
                        });
                });

            modelBuilder.Entity("PetCore.Domain.Entities.Protocolo", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Texto")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.HasKey("Id");

                    b.ToTable("protocolo_petcore", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "PROTO1",
                            Texto = "Pulgas, carrapatos e mosquitos podem transmitir doenças importantes aos pets. A prevenção pode ser feita com produtos tópicos, comprimidos ou coleiras específicas. Alguns produtos têm aplicação mensal, enquanto outros podem proteger por até três meses, conforme orientação do médico veterinário.",
                            Titulo = "Preventivo contra picadas"
                        },
                        new
                        {
                            Id = "PROTO2",
                            Texto = "A vermifugação ajuda a prevenir parasitas intestinais que podem causar perda de peso, diarreia, anemia e outros problemas. A frequência varia conforme idade, ambiente, hábitos do pet e risco de exposição.",
                            Titulo = "Vermifugação"
                        },
                        new
                        {
                            Id = "PROTO3",
                            Texto = "FIV e FeLV são doenças virais que acometem gatos. A testagem é importante, especialmente em felinos resgatados, com acesso à rua ou que convivem com outros gatos.",
                            Titulo = "FIV e FeLV"
                        });
                });

            modelBuilder.Entity("PetCore.Domain.Entities.Receita", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("IdMedicoResponsavel")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("IdProntuario")
                        .HasColumnType("char(36)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateOnly>("Validade")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.HasIndex("IdMedicoResponsavel");

                    b.HasIndex("IdProntuario");

                    b.ToTable("receita_petcore", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("a0000000-0000-0000-0000-000000000001"),
                            IdMedicoResponsavel = new Guid("40000000-0000-0000-0000-000000000001"),
                            IdProntuario = new Guid("70000000-0000-0000-0000-000000000001"),
                            Nome = "Receita dermatológica - Luna",
                            Validade = new DateOnly(2025, 12, 10)
                        },
                        new
                        {
                            Id = new Guid("a0000000-0000-0000-0000-000000000002"),
                            IdMedicoResponsavel = new Guid("40000000-0000-0000-0000-000000000002"),
                            IdProntuario = new Guid("70000000-0000-0000-0000-000000000002"),
                            Nome = "Receita preventiva - Tobias",
                            Validade = new DateOnly(2025, 12, 2)
                        });
                });

            modelBuilder.Entity("PetCore.Domain.Entities.Relatorio", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("IdHistorico")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("IdMedicoResponsavel")
                        .HasColumnType("char(36)");

                    b.Property<string>("Observacao")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("IdHistorico");

                    b.HasIndex("IdMedicoResponsavel");

                    b.ToTable("relatorio_petcore", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("b0000000-0000-0000-0000-000000000001"),
                            IdHistorico = new Guid("30000000-0000-0000-0000-000000000001"),
                            IdMedicoResponsavel = new Guid("40000000-0000-0000-0000-000000000001"),
                            Observacao = "Retorno sugerido em seis meses para acompanhamento preventivo."
                        },
                        new
                        {
                            Id = new Guid("b0000000-0000-0000-0000-000000000002"),
                            IdHistorico = new Guid("30000000-0000-0000-0000-000000000002"),
                            IdMedicoResponsavel = new Guid("40000000-0000-0000-0000-000000000002"),
                            Observacao = "Manter rotina de hidratação e retorno anual."
                        });
                });

            modelBuilder.Entity("PetCore.Domain.Entities.Tutor", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateOnly>("DataNascimento")
                        .HasColumnType("date");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Sexo")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("varchar(1)");

                    b.Property<string>("Telefone")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("UrlImg")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("tutor_petcore", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("60000000-0000-0000-0000-000000000001"),
                            DataNascimento = new DateOnly(1991, 11, 3),
                            Email = "marina.alves@exemplo.test",
                            Nome = "Marina Alves",
                            Senha = "SenhaDemo#2026",
                            Sexo = "F",
                            Telefone = "11991234567",
                            UrlImg = "https://exemplo.test/tutores/marina.jpg"
                        },
                        new
                        {
                            Id = new Guid("60000000-0000-0000-0000-000000000002"),
                            DataNascimento = new DateOnly(1988, 5, 25),
                            Email = "bruno.ferreira@exemplo.test",
                            Nome = "Bruno Ferreira",
                            Senha = "SenhaDemo#2026",
                            Sexo = "M",
                            Telefone = "11992345678",
                            UrlImg = "https://exemplo.test/tutores/bruno.jpg"
                        });
                });

            modelBuilder.Entity("rec_medic_petcore", b =>
                {
                    b.Property<Guid>("ID_medic_FK")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("ID_rec_FK")
                        .HasColumnType("char(36)");

                    b.HasKey("ID_medic_FK", "ID_rec_FK");

                    b.HasIndex("ID_rec_FK");

                    b.ToTable("rec_medic_petcore", (string)null);

                    b.HasData(
                        new
                        {
                            ID_medic_FK = new Guid("90000000-0000-0000-0000-000000000001"),
                            ID_rec_FK = new Guid("a0000000-0000-0000-0000-000000000001")
                        },
                        new
                        {
                            ID_medic_FK = new Guid("90000000-0000-0000-0000-000000000002"),
                            ID_rec_FK = new Guid("a0000000-0000-0000-0000-000000000002")
                        });
                });

            modelBuilder.Entity("rel_cli_petcore", b =>
                {
                    b.Property<Guid>("ID_cli_FK")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("ID_rel_FK")
                        .HasColumnType("char(36)");

                    b.HasKey("ID_cli_FK", "ID_rel_FK");

                    b.HasIndex("ID_rel_FK");

                    b.ToTable("rel_cli_petcore", (string)null);

                    b.HasData(
                        new
                        {
                            ID_cli_FK = new Guid("20000000-0000-0000-0000-000000000001"),
                            ID_rel_FK = new Guid("b0000000-0000-0000-0000-000000000001")
                        },
                        new
                        {
                            ID_cli_FK = new Guid("20000000-0000-0000-0000-000000000002"),
                            ID_rel_FK = new Guid("b0000000-0000-0000-0000-000000000002")
                        });
                });

            modelBuilder.Entity("tut_pet_petcore", b =>
                {
                    b.Property<Guid>("ID_tut_FK")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("ID_pet_FK")
                        .HasColumnType("char(36)");

                    b.HasKey("ID_tut_FK", "ID_pet_FK");

                    b.HasIndex("ID_pet_FK");

                    b.ToTable("tut_pet_petcore", (string)null);

                    b.HasData(
                        new
                        {
                            ID_tut_FK = new Guid("60000000-0000-0000-0000-000000000001"),
                            ID_pet_FK = new Guid("50000000-0000-0000-0000-000000000001")
                        },
                        new
                        {
                            ID_tut_FK = new Guid("60000000-0000-0000-0000-000000000002"),
                            ID_pet_FK = new Guid("50000000-0000-0000-0000-000000000002")
                        });
                });

            modelBuilder.Entity("PetCore.Domain.Entities.Clinica", b =>
                {
                    b.HasOne("PetCore.Domain.Entities.Endereco", "Endereco")
                        .WithOne("Clinica")
                        .HasForeignKey("PetCore.Domain.Entities.Clinica", "IdEndereco")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Endereco");
                });

            modelBuilder.Entity("PetCore.Domain.Entities.Exame", b =>
                {
                    b.HasOne("PetCore.Domain.Entities.Medico", "Medico")
                        .WithMany("Exames")
                        .HasForeignKey("IdMedico")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PetCore.Domain.Entities.Prontuario", "Prontuario")
                        .WithMany("Exames")
                        .HasForeignKey("IdProntuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Medico");

                    b.Navigation("Prontuario");
                });

            modelBuilder.Entity("PetCore.Domain.Entities.Historico", b =>
                {
                    b.HasOne("PetCore.Domain.Entities.Pet", "Pet")
                        .WithOne("Historico")
                        .HasForeignKey("PetCore.Domain.Entities.Historico", "IdPet")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Pet");
                });

            modelBuilder.Entity("PetCore.Domain.Entities.Prontuario", b =>
                {
                    b.HasOne("PetCore.Domain.Entities.Historico", "Historico")
                        .WithMany("Prontuarios")
                        .HasForeignKey("IdHistorico")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PetCore.Domain.Entities.Medico", "Medico")
                        .WithMany("Prontuarios")
                        .HasForeignKey("IdMedico")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Historico");

                    b.Navigation("Medico");
                });

            modelBuilder.Entity("PetCore.Domain.Entities.Receita", b =>
                {
                    b.HasOne("PetCore.Domain.Entities.Medico", "Medico")
                        .WithMany("Receitas")
                        .HasForeignKey("IdMedicoResponsavel")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PetCore.Domain.Entities.Prontuario", "Prontuario")
                        .WithMany("Receitas")
                        .HasForeignKey("IdProntuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Medico");

                    b.Navigation("Prontuario");
                });

            modelBuilder.Entity("PetCore.Domain.Entities.Relatorio", b =>
                {
                    b.HasOne("PetCore.Domain.Entities.Historico", "Historico")
                        .WithMany("Relatorios")
                        .HasForeignKey("IdHistorico")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PetCore.Domain.Entities.Medico", "Medico")
                        .WithMany("Relatorios")
                        .HasForeignKey("IdMedicoResponsavel")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Historico");

                    b.Navigation("Medico");
                });

            modelBuilder.Entity("rec_medic_petcore", b =>
                {
                    b.HasOne("PetCore.Domain.Entities.Medicamento", null)
                        .WithMany()
                        .HasForeignKey("ID_medic_FK")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PetCore.Domain.Entities.Receita", null)
                        .WithMany()
                        .HasForeignKey("ID_rec_FK")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });

            modelBuilder.Entity("rel_cli_petcore", b =>
                {
                    b.HasOne("PetCore.Domain.Entities.Clinica", null)
                        .WithMany()
                        .HasForeignKey("ID_cli_FK")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PetCore.Domain.Entities.Relatorio", null)
                        .WithMany()
                        .HasForeignKey("ID_rel_FK")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });

            modelBuilder.Entity("tut_pet_petcore", b =>
                {
                    b.HasOne("PetCore.Domain.Entities.Pet", null)
                        .WithMany()
                        .HasForeignKey("ID_pet_FK")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PetCore.Domain.Entities.Tutor", null)
                        .WithMany()
                        .HasForeignKey("ID_tut_FK")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });

            modelBuilder.Entity("PetCore.Domain.Entities.Endereco", b =>
                {
                    b.Navigation("Clinica")
                        .IsRequired();
                });

            modelBuilder.Entity("PetCore.Domain.Entities.Historico", b =>
                {
                    b.Navigation("Prontuarios");

                    b.Navigation("Relatorios");
                });

            modelBuilder.Entity("PetCore.Domain.Entities.Medico", b =>
                {
                    b.Navigation("Exames");

                    b.Navigation("Prontuarios");

                    b.Navigation("Receitas");

                    b.Navigation("Relatorios");
                });

            modelBuilder.Entity("PetCore.Domain.Entities.Pet", b =>
                {
                    b.Navigation("Historico");
                });

            modelBuilder.Entity("PetCore.Domain.Entities.Prontuario", b =>
                {
                    b.Navigation("Exames");

                    b.Navigation("Receitas");
                });
#pragma warning restore 612, 618
        }
    }
}
