// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PetCore.Infrastructure.Persistence;

#nullable disable

namespace PetCore.Infrastructure.Migrations
{
    [DbContext(typeof(PetCoreContext))]
    [Migration("20260522013558_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("PetCore.Domain.Entities.Clinica", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Cnpj")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<Guid>("IdEndereco")
                        .HasColumnType("char(36)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("IdEndereco")
                        .IsUnique();

                    b.ToTable("clinica_petcore", (string)null);
                });

            modelBuilder.Entity("PetCore.Domain.Entities.Endereco", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Cep")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Complemento")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("endereco_petcore", (string)null);
                });

            modelBuilder.Entity("PetCore.Domain.Entities.Exame", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateOnly>("Data")
                        .HasColumnType("date");

                    b.Property<Guid>("IdMedico")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("IdProntuario")
                        .HasColumnType("char(36)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("IdMedico");

                    b.HasIndex("IdProntuario");

                    b.ToTable("exame_petcore", (string)null);
                });

            modelBuilder.Entity("PetCore.Domain.Entities.Historico", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateOnly>("DataAbertura")
                        .HasColumnType("date");

                    b.Property<bool>("Status")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("Id");

                    b.ToTable("historico_petcore", (string)null);
                });

            modelBuilder.Entity("PetCore.Domain.Entities.Medicamento", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Dosagem")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Instrucao")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("medicamento_petcore", (string)null);
                });

            modelBuilder.Entity("PetCore.Domain.Entities.Medico", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateOnly>("DataNascimento")
                        .HasColumnType("date");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Especialidade")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Sexo")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("varchar(1)");

                    b.Property<string>("Telefone")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("UrlImg")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("medico_petcore", (string)null);
                });

            modelBuilder.Entity("PetCore.Domain.Entities.Pet", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateOnly>("DataNasc")
                        .HasColumnType("date");

                    b.Property<string>("Especie")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<Guid>("IdHistorico")
                        .HasColumnType("char(36)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Pelagem")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Porte")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Raca")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Sexo")
                        .HasColumnType("int");

                    b.Property<bool>("Status")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("UrlImg")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("IdHistorico")
                        .IsUnique();

                    b.ToTable("pet_petcore", (string)null);
                });

            modelBuilder.Entity("PetCore.Domain.Entities.Prontuario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateOnly>("DataEmissao")
                        .HasColumnType("date");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<Guid>("IdHistorico")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("IdMedico")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("IdHistorico");

                    b.HasIndex("IdMedico");

                    b.ToTable("prontuario_petcore", (string)null);
                });

            modelBuilder.Entity("PetCore.Domain.Entities.Receita", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("IdMedicoResponsavel")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("IdProntuario")
                        .HasColumnType("char(36)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateOnly>("Validade")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.HasIndex("IdMedicoResponsavel");

                    b.HasIndex("IdProntuario");

                    b.ToTable("receita_petcore", (string)null);
                });

            modelBuilder.Entity("PetCore.Domain.Entities.Relatorio", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("IdHistorico")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("IdMedicoResponsavel")
                        .HasColumnType("char(36)");

                    b.Property<string>("Observacao")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("IdHistorico");

                    b.HasIndex("IdMedicoResponsavel");

                    b.ToTable("relatorio_petcore", (string)null);
                });

            modelBuilder.Entity("PetCore.Domain.Entities.Tutor", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateOnly>("DataNascimento")
                        .HasColumnType("date");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Sexo")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("varchar(1)");

                    b.Property<string>("Telefone")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("UrlImg")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("tutor_petcore", (string)null);
                });

            modelBuilder.Entity("rec_medic_petcore", b =>
                {
                    b.Property<Guid>("ID_medic_FK")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("ID_rec_FK")
                        .HasColumnType("char(36)");

                    b.HasKey("ID_medic_FK", "ID_rec_FK");

                    b.HasIndex("ID_rec_FK");

                    b.ToTable("rec_medic_petcore", (string)null);
                });

            modelBuilder.Entity("rel_cli_petcore", b =>
                {
                    b.Property<Guid>("ID_cli_FK")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("ID_rel_FK")
                        .HasColumnType("char(36)");

                    b.HasKey("ID_cli_FK", "ID_rel_FK");

                    b.HasIndex("ID_rel_FK");

                    b.ToTable("rel_cli_petcore", (string)null);
                });

            modelBuilder.Entity("tut_pet_petcore", b =>
                {
                    b.Property<Guid>("ID_tut_FK")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("ID_pet_FK")
                        .HasColumnType("char(36)");

                    b.HasKey("ID_tut_FK", "ID_pet_FK");

                    b.HasIndex("ID_pet_FK");

                    b.ToTable("tut_pet_petcore", (string)null);
                });

            modelBuilder.Entity("PetCore.Domain.Entities.Clinica", b =>
                {
                    b.HasOne("PetCore.Domain.Entities.Endereco", "Endereco")
                        .WithOne("Clinica")
                        .HasForeignKey("PetCore.Domain.Entities.Clinica", "IdEndereco")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Endereco");
                });

            modelBuilder.Entity("PetCore.Domain.Entities.Exame", b =>
                {
                    b.HasOne("PetCore.Domain.Entities.Medico", "Medico")
                        .WithMany("Exames")
                        .HasForeignKey("IdMedico")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PetCore.Domain.Entities.Prontuario", "Prontuario")
                        .WithMany("Exames")
                        .HasForeignKey("IdProntuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Medico");

                    b.Navigation("Prontuario");
                });

            modelBuilder.Entity("PetCore.Domain.Entities.Pet", b =>
                {
                    b.HasOne("PetCore.Domain.Entities.Historico", "Historico")
                        .WithOne("Pet")
                        .HasForeignKey("PetCore.Domain.Entities.Pet", "IdHistorico")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Historico");
                });

            modelBuilder.Entity("PetCore.Domain.Entities.Prontuario", b =>
                {
                    b.HasOne("PetCore.Domain.Entities.Historico", "Historico")
                        .WithMany("Prontuarios")
                        .HasForeignKey("IdHistorico")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PetCore.Domain.Entities.Medico", "Medico")
                        .WithMany("Prontuarios")
                        .HasForeignKey("IdMedico")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Historico");

                    b.Navigation("Medico");
                });

            modelBuilder.Entity("PetCore.Domain.Entities.Receita", b =>
                {
                    b.HasOne("PetCore.Domain.Entities.Medico", "Medico")
                        .WithMany("Receitas")
                        .HasForeignKey("IdMedicoResponsavel")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PetCore.Domain.Entities.Prontuario", "Prontuario")
                        .WithMany("Receitas")
                        .HasForeignKey("IdProntuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Medico");

                    b.Navigation("Prontuario");
                });

            modelBuilder.Entity("PetCore.Domain.Entities.Relatorio", b =>
                {
                    b.HasOne("PetCore.Domain.Entities.Historico", "Historico")
                        .WithMany("Relatorios")
                        .HasForeignKey("IdHistorico")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PetCore.Domain.Entities.Medico", "Medico")
                        .WithMany("Relatorios")
                        .HasForeignKey("IdMedicoResponsavel")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Historico");

                    b.Navigation("Medico");
                });

            modelBuilder.Entity("rec_medic_petcore", b =>
                {
                    b.HasOne("PetCore.Domain.Entities.Medicamento", null)
                        .WithMany()
                        .HasForeignKey("ID_medic_FK")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PetCore.Domain.Entities.Receita", null)
                        .WithMany()
                        .HasForeignKey("ID_rec_FK")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });

            modelBuilder.Entity("rel_cli_petcore", b =>
                {
                    b.HasOne("PetCore.Domain.Entities.Clinica", null)
                        .WithMany()
                        .HasForeignKey("ID_cli_FK")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PetCore.Domain.Entities.Relatorio", null)
                        .WithMany()
                        .HasForeignKey("ID_rel_FK")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });

            modelBuilder.Entity("tut_pet_petcore", b =>
                {
                    b.HasOne("PetCore.Domain.Entities.Pet", null)
                        .WithMany()
                        .HasForeignKey("ID_pet_FK")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PetCore.Domain.Entities.Tutor", null)
                        .WithMany()
                        .HasForeignKey("ID_tut_FK")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });

            modelBuilder.Entity("PetCore.Domain.Entities.Endereco", b =>
                {
                    b.Navigation("Clinica")
                        .IsRequired();
                });

            modelBuilder.Entity("PetCore.Domain.Entities.Historico", b =>
                {
                    b.Navigation("Pet")
                        .IsRequired();

                    b.Navigation("Prontuarios");

                    b.Navigation("Relatorios");
                });

            modelBuilder.Entity("PetCore.Domain.Entities.Medico", b =>
                {
                    b.Navigation("Exames");

                    b.Navigation("Prontuarios");

                    b.Navigation("Receitas");

                    b.Navigation("Relatorios");
                });

            modelBuilder.Entity("PetCore.Domain.Entities.Prontuario", b =>
                {
                    b.Navigation("Exames");

                    b.Navigation("Receitas");
                });
#pragma warning restore 612, 618
        }
    }
}
